--------------------------------------------------------
--  File created - Monday-July-15-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VEHICLE_STATUS_LOOKUP
--------------------------------------------------------

  CREATE TABLE "DOT423"."VEHICLE_STATUS_LOOKUP" 
   (	"STATUS_CODE" VARCHAR2(3 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"STANDARD_STATUS_CODE" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
REM INSERTING into VEHICLE_STATUS_LOOKUP
SET DEFINE OFF;
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('0','Not Available (Assumed Current)','100');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('100','Original Carrier Fleet (Generic Active Vehicle Status)','100');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('101','All Credentials Issued','100');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('111','Partial Payment Not Yet Due','100');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('121','Vehicle Added On A Fleet To Fleet Transaction','100');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('131','Outstanding Temporary Authority','100');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('140','Vehicle Conversion Record','100');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('161','Activate Suspended Vehicle','100');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('201','Renewed Active Vehicle','100');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('501','Active Vehicle (Converted)','100');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('511','Inactive (Converted)','100');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('900','Not Current (Generic Inactive Vehicle Status)','900');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('901','Suspended Non Payment','900');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('911','Suspended (Weight Violation)','900');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('940','Vehicle Status Code Not Yet Assigned','900');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('941','Sleeping Vehicle','900');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('943','Prevents Credential Issuance','900');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('951','Vehicle Withdrawn From Operations For No Reported Reason','900');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('952','Vehicle Withdrawn From Operations Due To The Vehicle Needing Maintenance','900');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('953','Vehicle Withdrawn From Operations Due To The Vehicle Being Sold','900');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('954','Vehicle Withdrawn From Operations Due To The Vehicle Being Stolen','900');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('955','Vehicle Withdrawn From Operations Due To The Vehicle Being Wrecked','900');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('956','Vehicle Withdrawn From Operations Due To The Vehicle Being Salvaged','900');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('959','Vehicle Deleted On A Fleet Transaction','900');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('961','Vehicle Suspension Code','961');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('998','Vehicle Soft Deleted But Treated As Hard','900');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('999','Physically Deleted Vehicle','900');
Insert into VEHICLE_STATUS_LOOKUP (STATUS_CODE,DESCRIPTION,STANDARD_STATUS_CODE) values ('950','Federal out of service','950');
--------------------------------------------------------
--  DDL for Index PK_VEHICLE_STATUS_LOOKUP
--------------------------------------------------------

  CREATE UNIQUE INDEX "DOT423"."PK_VEHICLE_STATUS_LOOKUP" ON "DOT423"."VEHICLE_STATUS_LOOKUP" ("STATUS_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 16384 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEXES" ;
--------------------------------------------------------
--  Constraints for Table VEHICLE_STATUS_LOOKUP
--------------------------------------------------------

  ALTER TABLE "DOT423"."VEHICLE_STATUS_LOOKUP" MODIFY ("STATUS_CODE" NOT NULL ENABLE);
  ALTER TABLE "DOT423"."VEHICLE_STATUS_LOOKUP" ADD CONSTRAINT "PK_VEHICLE_STATUS_LOOKUP" PRIMARY KEY ("STATUS_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 16384 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEXES"  ENABLE;
  ALTER TABLE "DOT423"."VEHICLE_STATUS_LOOKUP" ADD SUPPLEMENTAL LOG GROUP "GGS_77313" ("STATUS_CODE") ALWAYS;
  ALTER TABLE "DOT423"."VEHICLE_STATUS_LOOKUP" ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
  ALTER TABLE "DOT423"."VEHICLE_STATUS_LOOKUP" ADD SUPPLEMENTAL LOG DATA (UNIQUE INDEX) COLUMNS;
  ALTER TABLE "DOT423"."VEHICLE_STATUS_LOOKUP" ADD SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS;
  ALTER TABLE "DOT423"."VEHICLE_STATUS_LOOKUP" ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
