--------------------------------------------------------
--  File created - Monday-July-15-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XDC_CATEGORY
--------------------------------------------------------

  CREATE TABLE "XDC_CATEGORY" 
   (	"CATEGORY_ID" NUMBER, 
	"CATEGORY_NAME" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 516096 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XML_DATA" ;
REM INSERTING into XDC_CATEGORY
SET DEFINE OFF;
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (0,'non-IRP CVIEW');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (1,'CVISN-only CVIEW');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (2,'Hybrid CVIEW');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (3,'PRISM-only CVIEW');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (4,'Data Standard - Rule #1');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (5,'Data Standard - Rule #2');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (6,'Data Standard - Rule #3');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (7,'Data Standard - Rule #4');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (8,'Data Standard - Rule #5');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (9,'Data Standard - Rule #6');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (10,'Data Standard - Rule #8');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (11,'Data Standard - Rule #8');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (12,'Check Transponder Number');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (13,'Convert Vehicle Type Code');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (14,'Convert IRP FLEET Status Code');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (16,'Data Standard Rule IFTA DOT');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (17,'IFTA LicenseNumber Standard Rule');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (15,'State can send other states file');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (18,'Check UCR Federal Identification');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (19,'Check UCR Registration Year');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (20,'Check UCR Upload Jurisdiction');
Insert into XDC_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (1000,'Temp - Indranil');
--------------------------------------------------------
--  DDL for Index PK_XDC_CATEGORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "DOT423"."PK_XDC_CATEGORY" ON "DOT423"."XDC_CATEGORY" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XML_INDEX" ;
--------------------------------------------------------
--  Constraints for Table XDC_CATEGORY
--------------------------------------------------------

  ALTER TABLE "DOT423"."XDC_CATEGORY" ADD CONSTRAINT "PK_XDC_CATEGORY" PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XML_INDEX"  ENABLE;
  ALTER TABLE "DOT423"."XDC_CATEGORY" ADD SUPPLEMENTAL LOG GROUP "GGS_77291" ("CATEGORY_ID") ALWAYS;
  ALTER TABLE "DOT423"."XDC_CATEGORY" ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
  ALTER TABLE "DOT423"."XDC_CATEGORY" ADD SUPPLEMENTAL LOG DATA (UNIQUE INDEX) COLUMNS;
  ALTER TABLE "DOT423"."XDC_CATEGORY" ADD SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS;
  ALTER TABLE "DOT423"."XDC_CATEGORY" ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
