--------------------------------------------------------
--  File created - Monday-July-15-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XDC_CATEGORY_FIELDS
--------------------------------------------------------

  CREATE TABLE "DOT423"."XDC_CATEGORY_FIELDS" 
   (	"CATEGORY_ID" NUMBER, 
	"FIELD_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 516096 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XML_DATA" ;
REM INSERTING into XDC_CATEGORY_FIELDS
SET DEFINE OFF;
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,0);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,1);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,2);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,3);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,4);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,5);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,6);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,7);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,8);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,9);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,10);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,11);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,12);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,14);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,15);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,16);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,32);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,34);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,35);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,36);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,37);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,39);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,42);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,45);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,46);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,47);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,48);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,49);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,50);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,51);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,52);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,53);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,54);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,55);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,56);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,57);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,59);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,60);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,61);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,77);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,79);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,80);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,81);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,82);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,84);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,85);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,99);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,108);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,109);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,110);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,111);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (0,112);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,0);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,1);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,2);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,3);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,4);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,5);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,6);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,7);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,8);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,9);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,10);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,11);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,12);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,14);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,15);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,16);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,17);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,32);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,34);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,35);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,36);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,37);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,39);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,42);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,45);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,46);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,47);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,48);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,49);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,50);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,51);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,52);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,53);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,54);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,55);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,56);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,57);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,59);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,60);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,61);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,62);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,77);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,79);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,80);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,81);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,82);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,84);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,85);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,88);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,90);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,91);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,94);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,99);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,108);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,109);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,110);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,111);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (1,112);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,0);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,1);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,2);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,3);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,4);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,5);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,6);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,7);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,8);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,9);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,10);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,11);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,12);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,14);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,15);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,16);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,17);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,32);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,34);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,35);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,36);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,37);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,39);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,42);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,44);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,45);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,46);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,47);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,48);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,49);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,50);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,51);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,52);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,53);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,54);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,55);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,56);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,57);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,59);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,60);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,61);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,62);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,77);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,79);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,80);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,81);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,82);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,84);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,85);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,87);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,88);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,90);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,91);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,94);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,99);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,108);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,109);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,110);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,111);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (2,112);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,0);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,1);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,2);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,3);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,4);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,5);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,6);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,7);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,8);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,9);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,10);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,11);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,12);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,14);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,15);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,16);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,32);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,34);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,35);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,36);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,39);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,42);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,44);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,45);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,46);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,47);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,48);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,49);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,50);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,51);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,52);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,53);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,54);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,55);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,56);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,57);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,59);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,60);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,61);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,77);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,79);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,80);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,81);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,84);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,85);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,87);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,89);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,92);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,93);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,99);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,108);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,109);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,111);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (3,112);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (4,19);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (4,22);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (4,28);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (4,43);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (4,64);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (4,67);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (4,73);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (4,86);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,20);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,21);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,23);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,24);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,25);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,26);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,27);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,29);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,30);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,33);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,65);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,66);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,68);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,69);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,70);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,71);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,72);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,74);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,75);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,78);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (5,100);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (6,37);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (6,82);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (7,18);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (7,38);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (7,63);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (7,83);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (7,102);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (9,31);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (9,76);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (9,101);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (10,95);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (10,97);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (11,96);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (11,98);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (12,103);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (13,104);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (14,105);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (16,106);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (17,107);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (18,113);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (19,114);
Insert into XDC_CATEGORY_FIELDS (CATEGORY_ID,FIELD_ID) values (20,115);
--------------------------------------------------------
--  DDL for Index PK_XDC_CATEGORY_FIELDS
--------------------------------------------------------

  CREATE UNIQUE INDEX "DOT423"."PK_XDC_CATEGORY_FIELDS" ON "DOT423"."XDC_CATEGORY_FIELDS" ("CATEGORY_ID", "FIELD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XML_INDEX" ;
--------------------------------------------------------
--  Constraints for Table XDC_CATEGORY_FIELDS
--------------------------------------------------------

  ALTER TABLE "DOT423"."XDC_CATEGORY_FIELDS" ADD SUPPLEMENTAL LOG GROUP "GGS_77290" ("CATEGORY_ID", "FIELD_ID") ALWAYS;
  ALTER TABLE "DOT423"."XDC_CATEGORY_FIELDS" ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
  ALTER TABLE "DOT423"."XDC_CATEGORY_FIELDS" ADD SUPPLEMENTAL LOG DATA (UNIQUE INDEX) COLUMNS;
  ALTER TABLE "DOT423"."XDC_CATEGORY_FIELDS" ADD SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS;
  ALTER TABLE "DOT423"."XDC_CATEGORY_FIELDS" ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
  ALTER TABLE "DOT423"."XDC_CATEGORY_FIELDS" ADD CONSTRAINT "PK_XDC_CATEGORY_FIELDS" PRIMARY KEY ("CATEGORY_ID", "FIELD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XML_INDEX"  ENABLE;
